### ISSUE TITLE
Running ./tools/build.sh out-of-the-box on Ubuntu 14.04 fails

### ISSUE THREAD

**Issue by neovom** [smanilov/irreducible-cfg#1]
I tried running the install script on an Ubuntu 14.04 machine (latest updates, with llvm-3.8 installed) but it failed since the script is expecting llvm-config to be an executable on the machine. Also, you assume that clang and clag++ are executables on the machine, which might not be the case - in my particular case, I have all of these suffixed with -3.8 (llvm-config-3.8, clang-3.8, clang++-3.8). Can you update the script (and your cmake) or update the README with instructions on what needs to be installed ?

**Comment by smanilov** [comment]
Sadly Ubuntu is a badly maintained distro :( Get some Arch :+1: 

This bug is getting in the way of an out-of-the-box build, amongst others:
https://bugs.launchpad.net/ubuntu/+source/llvm/+bug/1387011

Initially, I tried to get around it, but can't get it to work.

You need a working clang + libc++ configuration such that (as you've noticed) clang, clang++, and llvm-config are in your PATH.

I'm running it on Arch linux, clang 3.7.1, libc++ 1.

**Comment by smanilov** [comment]
See latest commit: https://github.com/smanilov/irreducible-cfg/commit/ec3fbc26900bd403653dd17096dee13b36b089af
